/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompanyTable: typeof import('./src/components/CompanyTable.vue')['default']
    CompanyTableRow: typeof import('./src/components/CompanyTableRow.vue')['default']
    CompositionComponent: typeof import('./src/components/CompositionComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableSection: typeof import('./src/components/TableSection.vue')['default']
    UserTable: typeof import('./src/components/UserTable.vue')['default']
    UserTableRow: typeof import('./src/components/UserTableRow.vue')['default']
  }
}
